# Generated by Django 5.2.7 on 2025-12-20 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_url', models.URLField(blank=True, null=True, verbose_name='CV')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='portfolio')),
                ('other_documents', models.TextField(blank=True, help_text="Liens séparés par des virgules ou JSON : ['lien1', 'lien2']", null=True, verbose_name='autres documents')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='submissions.submission', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'dossier de candidature',
                'verbose_name_plural': 'dossiers de candidature',
            },
        ),
    ]
