# Generated by Django 5.2.7 on 2026-01-04 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_activate_date_application_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv_url',
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter_file',
            field=models.FileField(blank=True, help_text='PDF ou Word, optionnel', null=True, upload_to='applications/cover_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='Lettre de motivation'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(default=1, help_text='PDF ou Word uniquement, max 10 Mo', upload_to='applications/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='CV'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='other_documents',
            field=models.TextField(blank=True, help_text='Liens supplémentaires séparés par virgule', null=True, verbose_name='autres documents'),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='portfolio (GitHub, site, etc.)'),
        ),
    ]
