# Generated by Django 5.2.7 on 2026-01-08 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_cv_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de disponibilité'),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En € brut annuel', max_digits=12, null=True, verbose_name='salaire souhaité'),
        ),
        migrations.AddField(
            model_name='application',
            name='ia_score',
            field=models.FloatField(default=0.0, help_text="Score de matching calculé par l'IA (0-100)", verbose_name='score IA'),
        ),
        migrations.AddField(
            model_name='application',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 5', null=True, verbose_name="années d'expérience"),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter_file',
            field=models.FileField(blank=True, help_text='Optionnel', null=True, upload_to='applications/cover_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'odt'])], verbose_name='lettre de motivation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(help_text='PDF, Word ou OpenDocument', upload_to='applications/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'odt'])], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='lien portfolio (GitHub, site personnel, etc.)'),
        ),
    ]
