# Generated by Django 5.2.7 on 2026-01-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.TextField(blank=True, help_text="Bref aperçu des compétences par rapport à l'offre (généré par l'IA)", verbose_name='résumé IA'),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='lien portfolio'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('shortlisted', 'Pré-sélectionné'), ('interview', 'Entretien planifié'), ('rejected', 'Rejeté'), ('accepted', 'Accepté')], default='pending', help_text="Mis à jour automatiquement par l'IA", max_length=30, verbose_name='statut de la candidature'),
        ),
    ]
