# Generated by Django 5.2.7 on 2025-12-20 10:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='exigences')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='responsabilités')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='localisation')),
                ('is_remote', models.BooleanField(default=False, verbose_name='télétravail')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'CDDC/Intérim'), ('internship', 'Stage'), ('freelance', 'Freelance')], default='full_time', max_length=20, verbose_name='type de contrat')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salaire minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salaire maximum')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='recruiters.recruiter', verbose_name='recruteur')),
            ],
            options={
                'verbose_name': "offre d'emploi",
                'verbose_name_plural': "offres d'emploi",
                'ordering': ['-published_at'],
            },
        ),
    ]
