# Generated by Django 5.2.9 on 2025-12-25 18:00

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
    ]
