# Generated by Django 5.2.7 on 2026-01-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_joboffer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('alternance', 'Alternance'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('interim', 'Intérim')], default='cdi', max_length=20, verbose_name='type de contrat'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='required_skills',
            field=models.TextField(blank=True, null=True, verbose_name='compétences requises'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('remote', 'Télétravail 100%'), ('hybrid', 'Hybride')], default='full_time', max_length=20, verbose_name='type de poste'),
        ),
    ]
