# Generated by Django 5.2.9 on 2026-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_joboffer_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=70, help_text="Score minimum (0-100) pour passer à l'étape suivante", verbose_name='pourcentage de réussite'),
        ),
    ]
