# Generated by Django 5.2.7 on 2026-01-05 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='score de matching (0-100)')),
                ('extracted_skills', models.JSONField(verbose_name='compétences extraites du CV/LM')),
                ('matching_skills', models.JSONField(verbose_name="compétences correspondantes à l'offre")),
                ('missing_skills', models.JSONField(verbose_name='compétences manquantes')),
                ('summary', models.TextField(verbose_name='résumé IA')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name="réponse brute de l'agent")),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'analyse IA',
                'verbose_name_plural': 'analyses IA',
            },
        ),
    ]
