# Generated by Django 5.2.7 on 2026-01-11 02:30

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('submissions', '0003_remove_submission_cover_letter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIAnalysisResult',
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('extracted_profile', models.JSONField(default=dict, help_text='Données structurées : compétences, expériences, diplômes, etc.', verbose_name='profil extrait')),
                ('matching_score', models.PositiveSmallIntegerField(default=0, help_text="Score de 0 à 100 calculé par l'IA", verbose_name='score de matching')),
                ('matching_details', models.JSONField(default=dict, help_text='Compétences correspondantes, manquantes, forces/faiblesses', verbose_name='détails du matching')),
                ('recommendation', models.CharField(choices=[('interview_high', 'Entretien prioritaire'), ('interview_medium', 'Entretien possible'), ('interview_low', 'Entretien optionnel'), ('wait', "À attendre / plus d'infos"), ('reject', 'Rejet recommandé')], default='wait', help_text='Action suggérée au recruteur', max_length=30, verbose_name='recommandation finale')),
                ('recommendation_reason', models.TextField(blank=True, help_text='Explication claire et concise de la recommandation', verbose_name='justification détaillée')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='date de traitement IA')),
                ('processing_duration', models.DurationField(blank=True, help_text='Temps total de calcul des 3 agents', null=True, verbose_name='durée du traitement')),
                ('ai_model_version', models.CharField(blank=True, help_text="Ex: 'gpt-4o-mini-2024-11', 'grok-beta'", max_length=50, verbose_name='version du modèle IA')),
                ('confidence', models.FloatField(default=0.0, help_text="Confiance de l'IA sur l'analyse (0.0 à 1.0)", verbose_name='niveau de confiance global')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='submissions.submission', verbose_name='candidature analysée')),
            ],
            options={
                'verbose_name': "résultat d'analyse IA",
                'verbose_name_plural': "résultats d'analyse IA",
                'ordering': ['-processed_at'],
            },
        ),
    ]
