# Generated by Django 5.2.7 on 2026-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_aianalysisresult_options_and_more'),
        ('submissions', '0003_remove_submission_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='raw_ai_response',
            field=models.JSONField(blank=True, default=dict, help_text='Réponse complète renvoyée par DeepSeek/Gemini - conservée pour transparence et debug', null=True, verbose_name="réponse brute JSON de l'IA"),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='raw_text_response',
            field=models.TextField(blank=True, help_text='Version texte complète avant parsing - utile pour recherche', null=True, verbose_name='réponse texte brute'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='ai_model_version',
            field=models.CharField(blank=True, help_text="Ex: 'deepseek-v3'", max_length=50, verbose_name='version du modèle IA'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='confidence',
            field=models.FloatField(default=0.0, help_text="Confiance globale de l'IA (0.0 à 1.0)", verbose_name='niveau de confiance'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='extracted_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Compétences, expériences, diplômes, etc.', verbose_name='profil extrait'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='matching_details',
            field=models.JSONField(blank=True, default=dict, help_text='Compétences correspondantes, manquantes, forces/faiblesses', verbose_name='détails matching'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='matching_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Score final de 0 à 100', verbose_name='score de matching'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de traitement'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='processing_duration',
            field=models.DurationField(blank=True, help_text='Temps total des agents IA', null=True, verbose_name='durée du traitement'),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='recommendation_reason',
            field=models.TextField(blank=True, help_text='Explication claire et concise', verbose_name='justification détaillée'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['submission', 'matching_score'], name='agent_aiana_submiss_31e93b_idx'),
        ),
    ]
