# Generated by Django 5.2.7 on 2025-12-20 18:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="Utilisé dans l'URL, ex: privacy, terms, cookies", max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('content', models.TextField(verbose_name='contenu')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'politique',
                'verbose_name_plural': 'politiques',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Nom de classe FontAwesome, ex: fa-briefcase, fa-search, fa-users', max_length=100, verbose_name='icône')),
                ('target', models.CharField(choices=[('candidate', 'Candidat'), ('recruiter', 'Recruteur'), ('both', 'Les deux')], default='both', max_length=20, verbose_name='cible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('value', models.CharField(help_text="Ex: '1 247', '+50%', '98%'", max_length=100, verbose_name='valeur')),
                ('icon', models.CharField(blank=True, help_text='Classe FontAwesome, ex: fa-briefcase, fa-users, fa-chart-line', max_length=100, null=True, verbose_name='icône')),
                ('is_dynamic', models.BooleanField(default=False, help_text='Si coché, la valeur sera calculée automatiquement en temps réel', verbose_name='dynamique')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'statistique',
                'verbose_name_plural': 'statistiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=200, verbose_name="nom de l'auteur")),
                ('author_role', models.CharField(blank=True, max_length=150, null=True, verbose_name='poste/fonction')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='entreprise')),
                ('content', models.TextField(verbose_name='témoignage')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5, verbose_name='note')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name="photo de l'auteur")),
                ('is_approved', models.BooleanField(default=False, verbose_name='approuvé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'témoignage',
                'verbose_name_plural': 'témoignages',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='nom complet')),
                ('role', models.CharField(choices=[('candidate', 'Candidat'), ('recruiter', 'Recruteur'), ('admin', 'Administrateur')], default='candidate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
    ]
