# Generated by Django 5.2.7 on 2026-01-22 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_testimonial_options_remove_policy_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created'], 'verbose_name': 'avis', 'verbose_name_plural': 'avis'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_role',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message',
            field=models.TextField(default=0, verbose_name='avis / témoignage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Validé par un admin pour être affiché publiquement', verbose_name='approuvé / visible'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Pour trier les témoignages sur la page d'accueil", verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5, help_text='Note de 1 à 5', verbose_name='note'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_approved', 'order'], name='users_testi_is_appr_c232b7_idx'),
        ),
    ]
