# Generated by Django 5.2.9 on 2026-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Validé par un admin pour être affiché publiquement', verbose_name='approuvé / visible'),
        ),
    ]
