# Generated by Django 5.2.7 on 2025-12-20 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name="nom de l'entreprise")),
                ('company_website', models.URLField(blank=True, null=True, verbose_name="site web de l'entreprise")),
                ('company_description', models.TextField(blank=True, null=True, verbose_name="description de l'entreprise")),
                ('company_logo_url', models.URLField(blank=True, null=True, verbose_name="logo de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='téléphone')),
                ('position', models.CharField(blank=True, help_text='Ex: Responsable RH, Talent Acquisition Manager', max_length=150, null=True, verbose_name='poste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'recruteur',
                'verbose_name_plural': 'recruteurs',
                'ordering': ['company_name'],
            },
        ),
    ]
