# Generated by Django 5.2.7 on 2025-12-28 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_joboffer_created_at_and_more'),
        ('recruiters', '0002_remove_recruiter_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiter',
            new_name='RecruiterProfile',
        ),
    ]
