# Generated by Django 5.2.9 on 2026-01-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_rename_recruiter_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_logo_url',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_logo_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="logo de l'entreprise"),
        ),
    ]
