# Generated by Django 5.2.9 on 2026-02-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_remove_recruiterprofile_company_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/recruiters/', verbose_name='photo de profil'),
        ),
    ]
