# Generated by Django 5.2.7 on 2026-01-11 02:02

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_application_availability_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedApplication',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_profile', models.JSONField(default=dict, help_text='Compétences, diplômes, expériences extraits', verbose_name='profil extrait')),
                ('matching_score', models.FloatField(default=0.0, help_text="Score de 0 à 100 calculé par l'IA", verbose_name='score de matching')),
                ('matching_details', models.JSONField(default=dict, help_text='Compétences correspondantes / manquantes', verbose_name='détails matching')),
                ('recommendation', models.CharField(choices=[('interview', 'Entretien recommandé'), ('wait', 'À attendre'), ('reject', 'Rejet recommandé')], default='wait', max_length=50, verbose_name='recommandation')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='justification de la recommandation')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_recruiter', models.BooleanField(default=False, help_text="Devient True après la date limite de l'offre ou manuellement", verbose_name='visible au recruteur')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_result', to='applications.application', verbose_name='candidature originale')),
            ],
            options={
                'verbose_name': 'candidature traitée IA',
                'verbose_name_plural': 'candidatures traitées IA',
                'ordering': ['-processed_at'],
            },
        ),
    ]
