# Generated by Django 5.2.7 on 2025-12-20 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='téléphone')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='localisation')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biographie')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='lien vers le CV')),
                ('profile_picture_url', models.URLField(blank=True, null=True, verbose_name='photo de profil')),
                ('years_of_experience', models.CharField(blank=True, help_text="Ex: '5 ans', 'Débutant', '10+'", max_length=50, null=True, verbose_name="années d'expérience")),
                ('desired_salary', models.CharField(blank=True, help_text="Ex: '50-60k €', 'Négociable'", max_length=100, null=True, verbose_name='salaire souhaité')),
                ('availability_date', models.DateField(blank=True, null=True, verbose_name='date de disponibilité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'candidat',
                'verbose_name_plural': 'candidats',
                'ordering': ['-created_at'],
            },
        ),
    ]
