# Generated by Django 5.2.7 on 2026-01-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_options_remove_candidate_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_url',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, default=1, help_text='Présentez-vous en quelques lignes (facultatif)', verbose_name='biographie / présentation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
