# Generated by Django 5.2.9 on 2026-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/candidates/', verbose_name='photo de profil'),
        ),
    ]
