# Generated by Django 5.2.7 on 2025-12-20 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('phone', 'Téléphonique'), ('video', 'Visio'), ('on_site', 'Sur site'), ('technical', 'Technique')], max_length=20, verbose_name="type d'entretien")),
                ('scheduled_at', models.DateTimeField(verbose_name='date et heure prévue')),
                ('location_or_link', models.CharField(blank=True, help_text='Adresse physique ou lien Zoom/Meet/Teams', max_length=500, null=True, verbose_name='lieu ou lien')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='submissions.submission', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'entretien',
                'verbose_name_plural': 'entretiens',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
