# Generated by Django 5.2.9 on 2026-01-28 18:29

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_application_resume_alter_application_portfolio_url_and_more'),
        ('jobs', '0004_joboffer_pass_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(blank=True, default=list, help_text="Liste des questions générées par l'IA", verbose_name='questions générées')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('pending_feedback', 'Attente retour')], default='scheduled', max_length=30, verbose_name='statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='date prévue')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application', verbose_name='candidature')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.joboffer', verbose_name="offre d'emploi")),
            ],
            options={
                'verbose_name': 'entretien',
                'verbose_name_plural': 'entretiens',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
