# Generated by Django 5.2.9 on 2026-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text="Format : {'1': 'réponse à la question 1', '2': '...'}", verbose_name='réponses du candidat'),
        ),
        migrations.AddField(
            model_name='interview',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de complétion par le candidat'),
        ),
    ]
