# Generated by Django 5.2.7 on 2025-12-20 10:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='lettre de motivation')),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('under_review', "En cours d'examen"), ('interview_scheduled', 'Entretien planifié'), ('rejected', 'Refusée'), ('accepted', 'Acceptée')], default='submitted', max_length=30, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='candidates.candidate', verbose_name='candidat')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='jobs.joboffer', verbose_name="offre d'emploi")),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-submitted_at'],
                'unique_together': {('candidate', 'job_offer')},
            },
        ),
    ]
