# Generated by Django 5.2.9 on 2025-12-25 18:00

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created'], 'verbose_name': 'candidature', 'verbose_name_plural': 'candidatures'},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_status',
            field=models.CharField(choices=[('submitted', 'Soumise'), ('under_review', "En cours d'examen"), ('interview_scheduled', 'Entretien planifié'), ('rejected', 'Refusée'), ('accepted', 'Acceptée')], default='submitted', max_length=30, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
    ]
