# Generated by Django 5.2.7 on 2026-01-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_status',
        ),
        migrations.AlterField(
            model_name='submission',
            name='candidate',
            field=models.ForeignKey(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='candidat'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumise'), ('under_review', "En cours d'examen"), ('interview_scheduled', 'Entretien planifié'), ('rejected', 'Refusée'), ('accepted', 'Acceptée')], default='submitted', max_length=30, verbose_name='statut'),
        ),
    ]
